# Generated by Django 2.1.7 on 2019-03-20 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('fav_sports', models.CharField(max_length=20)),
                ('pub_date', models.DateField()),
                ('pub_time', models.TimeField()),
                ('slam_body', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='slam',
            name='writer',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='slam.Writer'),
        ),
    ]
